include:
  - key: fod_manager
    PROJECT_NAME: "fod_manager"
    PROJECT_DIR: "ccs/fod"

  - key: ract_fw
    PROJECT_NAME: "ract_fw"
    PROJECT_DIR: "ccs/lib/ract_fw"

  - key: ucd_fw
    PROJECT_NAME: "ucd_fw"
    PROJECT_DIR: "ccs/lib/ucd_fw"

  - key: remote_actuator
    PROJECT_NAME: "remote_actuator"
    PROJECT_DIR: "ccs/remote_actuator"

  - key: remote_notification
    PROJECT_NAME: "remote_notification"
    PROJECT_DIR: "ccs/remote_notification"

  - key: rdm
    PROJECT_NAME: "rdm"
    PROJECT_DIR: "ccs/suggestion/rdm"

  - key: ucd
    PROJECT_NAME: "ucd"
    PROJECT_DIR: "ccs/ucd"

  - key: appops
    PROJECT_NAME: "ucd_fw"
    PROJECT_DIR: "common/appops"

  - key: app_manager
    PROJECT_NAME: "ucd_fw"
    PROJECT_DIR: "common/app_manager"

  - key: dam
    PROJECT_NAME: "dam"
    PROJECT_DIR: "common/dam/dam"

  - key: dcm
    PROJECT_NAME: "dcm"
    PROJECT_DIR: "common/dam/dcm"

  - key: calibration
    PROJECT_NAME: "calibration"
    PROJECT_DIR: "common/lib/calibration"

  - key: common_fw
    PROJECT_NAME: "common_fw"
    PROJECT_DIR: "common/lib/common_fw"

  - key: dbg_operation
    PROJECT_NAME: "dbg_operation"
    PROJECT_DIR: "common/lib/dbg_operation"

  - key: ds_operation
    PROJECT_NAME: "ds_operation"
    PROJECT_DIR: "common/lib/ds_operation"

  - key: fodservice
    PROJECT_NAME: "fodservice"
    PROJECT_DIR: "common/lib/fodservice"

  - key: jwt_verification
    PROJECT_NAME: "jwt_verification"
    PROJECT_DIR: "common/lib/jwt_verification"

  - key: mqtt_client
    PROJECT_NAME: "mqtt_client"
    PROJECT_DIR: "common/lib/mqtt_client"

  - key: notification
    PROJECT_NAME: "notification"
    PROJECT_DIR: "common/lib/notification"

  - key: sig_operation
    PROJECT_NAME: "sig_operation"
    PROJECT_DIR: "common/lib/sig_operation"

  - key: someip_client
    PROJECT_NAME: "someip_client"
    PROJECT_DIR: "common/lib/someip_client"

  - key: someip_serverops
    PROJECT_NAME: "someip_serverops"
    PROJECT_DIR: "common/lib/someip_serverops"

  - key: uds_operation
    PROJECT_NAME: "someip_serverops"
    PROJECT_DIR: "common/lib/uds_operation"

  - key: napp_manager
    PROJECT_NAME: "napp_manager"
    PROJECT_DIR: "common/napp_manager"

  - key: someip_gw
    PROJECT_NAME: "napp_manager"
    PROJECT_DIR: "common/someip/someip_gw"

  - key: someip_mng
    PROJECT_NAME: "someip_mng"
    PROJECT_DIR: "common/someip/someip_mng"

  - key: can_if
    PROJECT_NAME: "suppif_can_if"
    PROJECT_DIR: "common/supp_if/can_if"

  - key: notification_if
    PROJECT_NAME: "suppif_notification_if"
    PROJECT_DIR: "common/supp_if/notification_if"

  - key: fotamaster
    PROJECT_NAME: "fotamaster"
    PROJECT_DIR: "fota_rdiag/fota/fota_master/01_source/Master"

  - key: dca
    PROJECT_NAME: "rdiag -dca"
    PROJECT_DIR: "fota_rdiag/rdiag/dca/Workspace/app/DCA"

  - key: ddg
    PROJECT_NAME: "rdiag -ddg"
    PROJECT_DIR: "fota_rdiag/rdiag/ddg"