name: Build Job

on:
  workflow_call:
    inputs:
      TARGET_OS:
        required: true
        type: string
      CI_TOOL_PATH:
        required: true
        type: string
      BUILD_SCRIPTS_PATH:
        required: true
        type: string
      BUILD_SETTINGS_PATH:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        if: ${{ inputs.TARGET_OS == 'linux' }}
        uses: ./.github/workflows/build-linux
        with:
          BUILD_SCRIPTS_PATH: ${{ inputs.BUILD_SCRIPTS_PATH }}
      - uses: actions/checkout@v4
        if: ${{ inputs.TARGET_OS == 'windows' }}
        uses: ./.github/workflows/build-windows
        with:
          BUILD_SCRIPTS_PATH: ${{ inputs.BUILD_SCRIPTS_PATH }}
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.TARGET_OS }}-img
          path: ./target/nml/img/*
          retention-days: 7