on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  job1:
    runs-on: self-hosted
    strategy:
      matrix: ${{ fromJson(inputs.matrix) }}
    steps:
      - run: |
          echo "done."
          # echo "not"

