name: cicd pipeline

env:
  APP_NAME: "myapp"
  VERSION: "1.0.0"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Make shell script executable
        run: |
          chmod +x ./src/shell/sample1.sh
          chmod +x ./src/shell/sample2.sh

      - name: run script
        run: bash ./src/shell/sample1.sh

  call-child:
    uses: ./.github/workflows/child.yml
    with:
      # envコンテキスト全体、または特定のマップをJSON文字列化
      env_json: ${{ toJSON(env) }}
