name: cicd pipeline

on: [push]

jobs:
  build:
    runs-on: self-hosted

    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      # self-hosted runner用
      - name: Install yq
        shell: powershell
        run: |
          choco install yq -y
      - id: gen-matrix
        shell: powershell
        run: |
          $json = yq.exe -o=json '.' "$env:GITHUB_WORKSPACE\.github\projects_file.yml"
          echo "matrix=$json" >> $env:GITHUB_OUTPUT
  job:
    needs: build
    uses: ./.github/workflows/child.yml
    with: 
      ${{ needs.build.outputs.matrix }}
