name: cicd pipeline

on:
  push

env:
  CI_TOOL_PATH: ci/script
  CI_SETTINGS_PATH: ci/settings

  BUILD_SCRIPTS_PATH: ci/script/build
  BUILD_SETTINGS_PATH: ci/settings/build

  STATIC_ANALYSIS_SCRIPTS_PATH: ci/script/static_analysis
  STATIC_ANALYSIS_SETTINGS_PATH: ci/settings/static_analysis

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    env:
      PROJECTS_FILE: .github/projects_file.json
      CHANGED_FILES_RULES: changed-files.yml
    steps:
      - uses: actions/checkout@v4
      - name: install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Generate changed-files rules from PROJECTS_FILE
        run: |
          chmod +x .github/scripts/generate-changed-files.sh
          .github/scripts/generate-changed-files.sh
        shell: bash
      - name: Get all related files that have changed
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          files_yaml_from_source_file: ${{ env.CHANGED_FILES_RULES }}
      - name: Generate matrix info including which pipeline should be triggered
        id: gen-matrix
        run: |
          chmod +x .github/scripts/generate-matrix.sh
          .github/scripts/generate-matrix.sh
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          CHANGED_KEYS: ${{ steps.changed-files.outputs.changed_keys }}
        shell: bash

  build-job:
    name: Build | ${{ matrix.target_os_upper }}
    if: startsWith(github.ref_name, 'release/')
    strategy:
      matrix:
        target_os: [ 'linux', 'windows' ]
        target_os_upper: [ 'LINUX', 'WINDOWS' ]
    uses: ./.github/workflows/build.yml
    with:
      TARGET_OS: ${{ matrix.target_os }}
      CI_TOOL_PATH: ci/script
      BUILD_SCRIPTS_PATH: ci/script/build
      BUILD_SETTINGS_PATH: ci/settings/build

  Static-analysis:
    needs: detect-changes
    strategy:
      matrix: ${{ fromJSON(needs.detect-changes.outputs.matrix) }}
    uses: ./.github/workflows/code_verification.yml
    with:
      PROJECT_NAME: ${{ matrix.PROJECT_NAME }}
      PROJECT_DIR: ${{ matrix.PROJECT_DIR }}
      STATIC_ANALYSIS_SCRIPTS_PATH: ci/script/static_analysis
      STATIC_ANALYSIS_SETTINGS_PATH: ci/settings/static_analysis



