name: cicd pipeline

on: push

jobs:
  data-preparation:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    continue-on-error: true
    env:
      PROJECTS_FILE: .github/projects_file.yml
      CHANGED_FILES_RULES: change-files.yml
    steps:
      - uses: actions/checkout@v4
      - name: install yq
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y yq
      - name: Extract require data to generate changed files config
        shell: bash
        run: |
          echo "" > "$CHANGED_FILES_RULES"  # Clear output file

          # Get all top-level keys
          KEYS=$(yq e 'keys | .[]' "$STRUCTURE_FILPROJECTS_FILE")

          for key in $KEYS; do
            echo "$key:" >> "$CHANGED_FILES_RULES"
            yq e ".$key.FILES_CHANGED_TRIGGER[]" "$PROJECTS_FILE" | while read pattern; do
              echo "  - \"$pattern\"" >> "$CHANGED_FILES_RULES"
            done
          done
          cat ${{ env.CHANGED_FILES_RULES }}
        shell: bash
      - name: Get all related files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v47
        with:
          files_yaml_from_source_file: ${{ env.CHANGED_FILES_RULES }}
      - name: Generate matrix info including which pipeline should be triggered
        id: gen-matrix
        run: |
          if [[ ${{ github.ref_name }} =~ ^release ]]; then
            DEPLOY_TARGET=$(yq e 'keys | .[]' "$PROJECTS_FILE")
            echo "Run release workflow..."
            echo "All projects will be selected as deploy target."
          else
            DEPLOY_TARGET=${{ steps.changed-files-yaml.outputs.changed_keys }}
            echo "The following projects will be triggered."
            echo "$DEPLOY_TARGET"
          fi
          json="["
          for key in $DEPLOY_TARGET; do
            PROJECT_NAME=$(yq e ".${key}.PROJECT_NAME" ${{ env.PROJECTS_FILE }})
            PROJECT_DIR=$(yq e ".${key}.PROJECT_DIR" ${{ env.PROJECTS_FILE }})
            json="${json}{\"PROJECT_NAME\":\"$PROJECT_NAME\",\"PROJECT_DIR\":\"$PROJECT_DIR\"},"
          done
          json="${json%,}]"
          echo "matrix=$json" >> $GITHUB_OUTPUT
        shell: bash


  build-job:
    name: Build - ${{ matrix.target_os }}
    needs: data-preparation
    runs-on: self-hosted # PCU-BUILD-EC2
    if: startsWith(github.ref_name, 'release/')
    continue-on-error: true
    strategy:
      matrix:
        target_os: [linux, windows, qnx]
    steps:
      - uses: actions/checkout@v4
      - name: Build for Linux
        if: matrix.target_os == 'linux'
        shell: bash
        run: |
          echo "Building for Linux..."
          echo "Executing build job for Linux environment by default."
          : # bash ${{ vars.BUILD_SCRIPTS_PATH }}/make.sh
          : # bash ${{ vars.BUILD_SCRIPTS_PATH }}/install_linux.sh
      - name: Build for Windows
        if: matrix.target_os == 'windows'
        shell: bash
        run: |
          echo "Building for Windows..."
      - name: Build for QNX
        if: matrix.target_os == 'qnx'
        shell: bash
        run: |
          echo "Building for QNX..."
          : # source /home/xw2/qnx710/qnxsdp-env.sh
          echo "Executing build job for QNX environment."
          : # ./make.sh --qnx
          : # echo "Completed build.. Packaging artifacts"
          : # bash ${{ vars.BUILD_SCRIPTS_PATH }}/install_linux.sh
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target_os }}-img
          path: ./target/nml/img/*
          retention-days: 7


  static-analysis:
    needs: data-preparation
    uses: ./.github/workflows/code-verification.yml
    with:
      PROJECT_NAME: ${{ matrix.pair.PROJECT_NAME }}
      PROJECT_DIR: ${{ matrix.pair.PROJECT_DIR }}
      STATIC_ANALYSIS_SCRIPTS_PATH: ${{ vars.STATIC_ANALYSIS_SCRIPTS_PATH }}
      STATIC_ANALYSIS_SETTINGS_PATH: ${{ vars.STATIC_ANALYSIS_SETTINGS_PATH }}
    strategy:
      matrix:
        include: ${{ fromJson(needs.data-preparation.outputs.matrix) }}


  static-analysis-summary:
    needs: static-analysis
    runs-on: self-hosted # PCU-POLYSPACE-EC2
    continue-on-error: true
    steps:
      - run: |
          echo "Run ID is ${{ github.run_id }}"
          : # bash ${{ vars.STATIC_ANALYSIS_SCRIPTS_PATH }}/get_failed_job_info.sh ${{ github.run_id }}
          : # bash ${{ vars.STATIC_ANALYSIS_SCRIPTS_PATH }}/get_execution_time_info.sh ${{ github.run_id }}
          : # bash ${{ vars.STATIC_ANALYSIS_SCRIPTS_PATH }}/summarize_error_count.sh ${{ github.run_id }}
          : # ls -l
        shell: bash
      - name: Upload Static Analysis Summary Report
        uses: actions/upload-artifact@v4
        with:
          name: static-analysis-summary-report
          path: |
            ./failed_jobs_info_${{ github.run_id }}.csv
            ./pipeline_execution_time_info_${{ github.run_id }}.csv
            ./error_count_summary_${{ github.run_id }}.csv
          retention-days: 30