name: cicd pipeline

on:
  push

env:
  CI_TOOL_PATH: ci/script
  CI_SETTINGS_PATH: ci/settings

  BUILD_SCRIPTS_PATH: ci/script/build
  BUILD_SETTINGS_PATH: ci/settings/build

  STATIC_ANALYSIS_SCRIPTS_PATH: ci/script/static_analysis
  STATIC_ANALYSIS_SETTINGS_PATH: ci/settings/static_analysis

jobs:

  build-job:
    name: Build | $ {{ matrix.target_os_upper }}
    runs-on: self-hosted
    if: startsWith(github.ref_name, 'release/')
    continue-on-error: true
    strategy:
      matrix:
        target_os: [ 'linux', 'windows' ]
        target_os_upper: [ 'LINUX', 'WINDOWS' ]
    uses: ./.github/workflows/build.yml
    with:
      TARGET_OS: ${{ matrix.target_os }}
      CI_TOOL_PATH: $CI_TOOL_PATH
      BUILD_SCRIPTS_PATH: $BUILD_SCRIPTS_PATH
      BUILD_SETTINGS_PATH: $BUILD_SETTINGS_PATH

  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          MATRIX_JSON=$(cat projects.json)
          echo "matrix=$MATRIX_JSON" >> "$GITHUB_OUTPUT"

  per-project-job:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Show project info
        run: |
          echo "project_id   = ${{ matrix.project_id }}"
          echo "name         = ${{ matrix.PROJECT_NAME }}"
          echo "dir          = ${{ matrix.PROJECT_DIR }}"
          echo "triggers     = ${{ join(matrix.FILES_CHANGED_TRIGGER, ', ') }}"

  Static-analysis:
    needs: build-matrix
    uses: ./.github/workflows/static_analysis/code_verification.yml
    with:
      PROJECT_NAME: ${{ matrix.PROJECT_NAME }}
      PROJECT_DIR: ${{ matrix.PROJECT_DIR }}
      CI_TOOL_PATH: $CI_TOOL_PATH
      CI_SETTINGS_PATH: $CI_SETTINGS_PATH
      BUILD_SCRIPTS_PATH: $BUILD_SCRIPTS_PATH
      BUILD_SETTINGS_PATH: $BUILD_SETTINGS_PATH
      STATIC_ANALYSIS_SCRIPTS_PATH: $STATIC_ANALYSIS_SCRIPTS_PATH
      STATIC_ANALYSIS_SETTINGS_PATH: $STATIC_ANALYSIS_SETTINGS_PATH
    strategy:
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}


