name: cicd pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Make shell script executable
        run: |
          chmod +x ./src/shell/sample1.sh
          chmod +x ./src/shell/sample2.sh
