on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  Bug-Finder:
    runs-on: self-hosted #PCU-POLYSPACE-EC2
    strategy:
      matrix: ${{ fromJson(inputs.matrix) }}
    env:
      PROJECT_NAME: ${{ matrix.PROJECT_NAME }}
      PROJECT_DIR: ${{ matrix.PROJECT_DIR }}
    steps:
      - uses: actions/checkout@v4
      - name: check1
        run: |
          echo "Project Name: ${{ env.PROJECT_NAME  }}"
          echo "Project Directory: ${{ env.PROJECT_DIR }}"