name: Code Verification

on:
  workflow_call:
    inputs:
      matrix:
        description: 'Matrix of projects for static analysis'
        required: true
        type: string
      STATIC_ANALYSIS_SCRIPTS_PATH:
        description: 'Path to static analysis scripts'
        required: true
        type: string
      STATIC_ANALYSIS_SETTINGS_PATH:
        description: 'Path to static analysis settings'
        required: true
        type: string

jobs:
  Bug-Finder:
    runs-on: self-hosted # PCU-POLYSPACE-EC2
    continue-on-error: true
    strategy:
      matrix:
        include: ${{ fromJson(inputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: check
        run: echo ${PROJECT_NAME}-${PROJECT_DIR}