name: Static Analysis

on:
  workflow_call:
    inputs:
      PROJECT_MATRIX:
        required: true
        type: string
      STATIC_ANALYSIS_SCRIPTS_PATH:
        required: true
        type: string
      STATIC_ANALYSIS_SETTINGS_PATH:
        required: true
        type: string

jobs:
  Bug-Finder:
    name: Code-Verification | Bug-Finder | ${{ matrix.project.PROJECT_NAME }}
    runs-on: self-hosted
    continue-on-error: true
    strategy:
      matrix:
        project: ${{ fromJSON(inputs.PROJECT_MATRIX) }}
    steps:
      - uses: actions/checkout@v4
      - name: Bug Finder
        shell: bash
        run: |
          echo "/opt/MathWorks/R2024b/polyspace/bin/polyspace-bug-finder-server \
            -options-file \"${{ matrix.project.PROJECT_DIR }}/app_common_option.txt\" \
            -options-file \"${{ matrix.project.PROJECT_DIR }}/app_bf_option.txt\" \
            -options-file \"${{ inputs.STATIC_ANALYSIS_SETTINGS_PATH }}/bug-finder-options.txt\" \
            -checkers-selection-file \"${{ inputs.STATIC_ANALYSIS_SETTINGS_PATH }}/custom_config.xml\" \
            -report-output-name \"${{ matrix.project.PROJECT_NAME }}_BugFinder\""
      - run: echo ls -l
      - run: echo python3 "${{ inputs.STATIC_ANALYSIS_SCRIPTS_PATH }}/print_error_count.py" bf "./bug-finder-results/Polyspace-Doc/${{ matrix.project.PROJECT_NAME }}_BugFinder.html"
      - name: Upload Bug-Finder Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project.PROJECT_NAME }}-Bug-Finder-${{ github.run_id }}
          path: ./bug-finder-results/**/*
          retention-days: 30

  Code-Prover:
    name: Code-Verification | Code-Prover | ${{ matrix.project.PROJECT_NAME }}
    runs-on: self-hosted
    continue-on-error: true
    strategy:
      matrix:
        project: ${{ fromJSON(inputs.PROJECT_MATRIX) }}
    steps:
      - uses: actions/checkout@v4
      - name: Code Prover
        shell: bash
        run: |
          echo "/opt/MathWorks/R2024b/polyspace/bin/polyspace-code-prover-server \
            -options-file \"${{ matrix.project.PROJECT_DIR }}/app_common_option.txt\" \
            -options-file \"${{ matrix.project.PROJECT_DIR }}/app_cp_option.txt\" \
            -options-file \"${{ inputs.STATIC_ANALYSIS_SETTINGS_PATH }}/code-prover-options.txt\" \
            -report-output-name \"${{ matrix.project.PROJECT_NAME }}_CodeProver\""
      - run: echo ls -l
      - run: echo python3 "${{ inputs.STATIC_ANALYSIS_SCRIPTS_PATH }}/print_error_count.py" cp "./code-prover-results/Polyspace-Doc/${{ matrix.project.PROJECT_NAME }}_CodeProver.html"
      - name: Upload Code-Prover Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project.PROJECT_NAME }}-Code-Prover-${{ github.run_id }}
          path: ./code-prover-results/**/*
          retention-days: 30