on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  Bug-Finder:
    runs-on: self-hosted # PCU-POLYSPACE-EC2
    continue-on-error: true
    strategy:
      matrix:
        include: ${{ fromJson(inputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: check
        run: echo ${PROJECT_NAME}-${PROJECT_DIR}