name: Complex job

on: 
  workflow_dispatch:
    inputs:
      target:
        description: "実行するターゲット（カンマ区切り: job1,job3 など）"
        required: true
        default: "sample1, sample2, sample3"

jobs:
  complex-job:
    runs-on: self-hosted
    continue-on-error: true
    strategy:
      matrix:
        target: [sample1, sample2, sample3]
      fail-fast: false
    environment: ${{ matrix.target }}

    steps:
      - if: contains( github.event.inputs.target, matrix.target )
        run: echo "${{ matrix.target }}"
        shell: bash

  job:
    runs-on: self-hosted
    needs: [complex-job]
    steps:
      - run: echo "job"
